version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-laravel-app
    container_name: my-laravel-app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=local
      - APP_KEY=base64:g1lBxh/x5Ty5+5v1JgIJrOb5eDCR8WdtbRjvDeh2ylo=
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/database.sqlite
    command: sh -c "php artisan migrate:fresh && php artisan db:seed && php artisan serve" && tail -f /dev/null"
